# -*- coding: utf-8 -*-
[PATHS]
# input/output# Radice del progetto (se vuoto, viene calcolata automaticamente dal codice)
data_dir = data
earthquakes_filename = query.txt
ground_truth_filename = ground_truth.jsonl

# Directory di output per i risultati di valutazione
evaluation_dir = evaluation
evaluation_results_filename = results.json

[INGESTION]
# Codifiche da tentare nell'apertura del file eventi (separate da virgola)
encodings_to_try = utf-8, utf-8-sig, cp1252, iso-8859-1
# Delimitatore del file eventi INGV
csv_delimiter = |

[TEXT_PROCESSING]
# Parametri per lo splitter
chunk_size = 400
chunk_overlap = 40

[RETRIEVAL]
# Numero di documenti da recuperare
top_k = 100

[LOGIC]
# Campi disponibili nel file INGV
event_id_key = EventID
time_key = Time
latitude_key = Latitude
longitude_key = Longitude
depth_key = Depth_Km
magnitude_key = Magnitude
magtype_key = MagType
location_key = EventLocationName
event_type_key = EventType
author_key = Author
catalog_key = Catalog
project_root =


